### PR TITLE
Group6 homework

### PR DESCRIPTION
**Pull request by JennyZHJ**
group 6: Haijing ZHU, Zhen XING, Ting ZHU, You SHAN, Huajuan ZHOU

### CODE REVIEW

**Comment by JennyZHJ** [comment]
group 6

**Comment by JennyZHJ** [comment]
add homework 1 is the revised edition, please check it, thank you!

**Comment by JennyZHJ** [comment]
Please read the one named group6-hw1, thank you!

**Comment by natashawatkins** [comment]
Hi I have added your homework here: https://github.com/QuantEcon/ShenzhenWinterCamp/tree/master/Homework/Group6

Please update your repository and add new homework here.

**Pull request closed without merging**
